version: '3'
services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./data/portainer:/data
    ports:
      - 9000:9000

  app:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-manager
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./config.json:/app/config/production.json
      - ./data/nginx-manager:/data
      - ./data/letsencrypt:/etc/letsencrypt

  db:
    image: yobasystems/alpine-mariadb:latest
    container_name: mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 'npm'
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'npm'
      MYSQL_PASSWORD: 'npm'
    volumes:
      - ./data/mysql:/var/lib/mysql

  deluge:
      image: linuxserver/deluge
      container_name: deluge
      restart: unless-stopped
      volumes:
      - ./data/deluge:/config
      - ./ext-hdd/trrntz:/downloads
      env_file: ./.env
      ports:
        - 8112:8112
        - 6881:6881
        - 6881:6881/udp

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    restart: unless-stopped
    ports:
      - 8989:8989
    volumes:
      - ./data/sonarr:/config
      - ./ext-hdd/trrntz:/downloads
    env_file: ./.env

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    env_file: ./.env
    volumes:
      - ./data/radarr:/config
      - ./ext-hdd/trrntz:/downloads
    ports:
      - 7878:7878

  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - PLEX_CLAIM=claim-a1Hqyd_VrGxtWBZRvpab
    volumes:
      - ./data/plex:/config
      - ./ext-hdd/trrntz:/media
      - ./data/plex-transcode:/transcode

  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    restart: unless-stopped
    env_file: ./.env
    volumes:
      - ./data/heimdall:/config
    ports:
      - 8088:80

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    restart: unless-stopped
    env_file: ./.env
    volumes:
      - ./data/prowlarr:/config
    ports:
      - 9696:9696
    